-- ============================================================
-- SQL SCRIPT: Create event_categories table
-- Run this in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/zkzotagctwqthxypczej/sql/new
-- ============================================================

CREATE TABLE IF NOT EXISTS public.event_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.event_categories ENABLE ROW LEVEL SECURITY;

-- Drop policies if they already exist
DROP POLICY IF EXISTS "Anyone can manage event categories" ON public.event_categories;
DROP POLICY IF EXISTS "Public read event categories" ON public.event_categories;

-- Create policy to allow managing event categories (ALL operations)
CREATE POLICY "Anyone can manage event categories"
  ON public.event_categories FOR ALL
  USING (true)
  WITH CHECK (true);

-- Create policy to allow public reading of event categories
CREATE POLICY "Public read event categories"
  ON public.event_categories FOR SELECT
  USING (true);

-- Insert default categories to seed the table
INSERT INTO public.event_categories (name)
VALUES ('Bhajans'), ('Seva'), ('Study Circle'), ('Celebration')
ON CONFLICT (name) DO NOTHING;
