-- ============================================================
-- SQL SCRIPT: Fix Phone Nullability and Event Categories
-- Run this in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/zkzotagctwqthxypczej/sql/new
-- ============================================================

-- 1. Drop the NOT NULL constraint from phone to allow email-only / Google OAuth registrations
ALTER TABLE public.members ALTER COLUMN phone DROP NOT NULL;

-- 2. Create the event_categories table if it is missing
CREATE TABLE IF NOT EXISTS public.event_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 3. Enable RLS and set policies
ALTER TABLE public.event_categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read event categories" ON public.event_categories;
DROP POLICY IF EXISTS "Anyone can manage event categories" ON public.event_categories;

CREATE POLICY "Anyone can manage event categories"
  ON public.event_categories FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Public read event categories"
  ON public.event_categories FOR SELECT
  USING (true);

-- 4. Seed default event categories
INSERT INTO public.event_categories (name)
VALUES ('Bhajans'), ('Seva'), ('Study Circle'), ('Celebration')
ON CONFLICT (name) DO NOTHING;
