"""
open_supabase_sql.py  –  Opens the Supabase SQL editor and copies the fix SQL to your clipboard.
Run: python quote/open_supabase_sql.py
Then paste (Ctrl+V) in the editor and click Run.
"""
import webbrowser
import subprocess
import sys

SQL = r"""ALTER TABLE public.members ALTER COLUMN phone DROP NOT NULL;

CREATE TABLE IF NOT EXISTS public.event_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.event_categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read event categories" ON public.event_categories;
DROP POLICY IF EXISTS "Anyone can manage event categories" ON public.event_categories;

CREATE POLICY "Anyone can manage event categories"
  ON public.event_categories FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Public read event categories"
  ON public.event_categories FOR SELECT
  USING (true);

INSERT INTO public.event_categories (name)
VALUES ('Bhajans'), ('Seva'), ('Study Circle'), ('Celebration')
ON CONFLICT (name) DO NOTHING;
"""

# Copy SQL to clipboard using PowerShell
try:
    proc = subprocess.run(
        ["powershell", "-Command", f"Set-Clipboard -Value @'\n{SQL}\n'@"],
        capture_output=True, text=True
    )
    print("SQL copied to clipboard successfully!")
except Exception as e:
    print(f"Clipboard copy failed: {e}")
    print("\nPlease manually copy the SQL below:\n")
    print(SQL)

# Open Supabase SQL editor
url = "https://supabase.com/dashboard/project/zkzotagctwqthxypczej/sql/new"
webbrowser.open(url)
print(f"\nOpened: {url}")
print("Please paste (Ctrl+V) in the SQL editor and click Run.")
