-- ============================================================
-- TABLE: quotes
-- Stores daily quotes of Sathya Sai Baba and Maha Periyava
-- ============================================================
CREATE TABLE IF NOT EXISTS public.quotes (
  id            BIGSERIAL PRIMARY KEY,
  guru          TEXT NOT NULL, -- 'sai' or 'periyava'
  quote_english TEXT NOT NULL,
  quote_tamil   TEXT NOT NULL,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Configuration
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;

-- Select policy: public read
CREATE POLICY "Public read quotes" ON public.quotes
  FOR SELECT USING (true);

-- Insert policy: anyone can insert
CREATE POLICY "Anyone can manage quotes" ON public.quotes
  FOR ALL USING (true) WITH CHECK (true);

-- Seed quotes data
INSERT INTO public.quotes (guru, quote_english, quote_tamil) VALUES
  ('sai', 'Love all. Serve all. Help ever. Hurt never.', 'அனைவரையும் நேசி. அனைவருக்கும் சேவை செய். எப்போதும் உதவு. ஒருபோதும் வலிக்கவிடாதே.'),
  ('sai', 'The greatest fear man can have is the fear of losing God''s Love.', 'மனிதனுக்கு இருக்கக்கூடிய மிகப்பெரிய பயம், இறைவனின் அன்பை இழந்துவிடுவோம் என்ற பயமே.'),
  ('sai', 'Money comes and goes; morality comes and grows.', 'பணம் வரும், போகும்; ஒழுக்கம் வரும், வளரும்.'),
  ('sai', 'Where there is Faith, there is Love; where there is Love, there is Peace; where there is Peace, there is God.', 'நம்பிக்கை இருக்கும் இடத்தில் அன்பு உண்டு; அன்பு இருக்கும் இடத்தில் அமைதி உண்டு; அமைதி இருக்கும் இடத்தில் இறைவன் உண்டு.'),
  ('sai', 'The end of knowledge is Love. The end of education is character.', 'அறிவின் முடிவு அன்பு; கல்வியின் முடிவு நற்குணம்.'),
  ('sai', 'Before you speak, ask yourself: is it kind, is it necessary, is it true, does it improve the silence?', 'பேசுவதற்கு முன் உன்னையே கேள்: இது அன்பானதா, இது தேவையானதா, இது உண்மையா, இது மௌனத்தை விட சிறந்ததா?'),
  ('sai', 'Do good, be good and see good. Do everything with love.', 'நன்மை செய், நல்லவனாக இரு, நன்மையை பார். எல்லாவற்றையும் அன்புடன் செய்.'),
  ('sai', 'Prayer must emanate from the heart, where God resides, and not from the head where doctrines and doubts clash.', 'பிரார்த்தனை இறைவன் வசிக்கும் இதயத்திலிருந்து வரவேண்டும்; கொள்கைகளும் சந்தேகங்களும் மோதிக்கொள்ளும் மனதிலிருந்து அல்ல.'),
  ('sai', 'Once we surrender our mind to God completely, He will take care of us in every way.', 'நம் மனதை முழுவதும் இறைவனிடம் சமர்பித்தால், அவன் எல்லா விதத்திலும் நம்மை காத்துக்கொள்வான்.'),
  ('sai', 'The secret of perfect health lies in keeping the mind always cheerful — never worried, never hurried, never borne down by fear.', 'நிறைவான ஆரோக்கியத்தின் இரகசியம் மனதை எப்போதும் மகிழ்ச்சியாக வைத்துக்கொள்வதே — கவலை வேண்டாம், அவசரம் வேண்டாம், பயம் வேண்டாம்.'),
  ('sai', 'God, if you think, God you are. Dust if you think, dust you are. As you think, so you become.', 'இறைவனை நினைத்தால் இறைவனாவாய்; தூசியை நினைத்தால் தூசியாவாய். நீ நினைப்பதுவே ஆவாய்.'),
  ('sai', 'You can hear the footsteps of God when silence reigns in the mind.', 'மனதில் மௌனம் நிலவும்போது இறைவனின் காலடி சத்தத்தை கேட்கலாம்.'),
  ('sai', 'Politics without principles, Education without character, Science without humanity — are not only useless, but dangerous.', 'கொள்கையற்ற அரசியல், குணமற்ற கல்வி, மனிதாபிமானமற்ற அறிவியல் — பயனற்றவை மட்டுமல்ல, ஆபத்தானவை.'),
  ('sai', 'Hear good things, see good, do good, think good — then you get the Grace of God.', 'நல்லதை கேள், நல்லதை பார், நல்லது செய், நல்லதை நினை — அப்போது இறைவனின் அருள் கிடைக்கும்.'),
  ('sai', 'Service springs out of Love and it scatters Love in profusion.', 'சேவை அன்பிலிருந்து பிறக்கிறது; அது அன்பை தாராளமாக பரப்புகிறது.'),
  ('sai', 'Silence is the speech of the spiritual seeker.', 'மௌனமே ஆன்மீக தேடலாளனின் பேச்சு.'),
  ('sai', 'Small minds select narrow roads; expand your mental vision and take the broad road of compassion and service.', 'சிறிய மனங்கள் குறுகிய வழிகளை தேர்வு செய்யும்; உன் மன நோக்கத்தை விரிவாக்கி கருணையும் சேவையும் நிறைந்த பரந்த பாதையை தேர்.'),
  ('sai', 'Ignorance is the most important cause of sorrow.', 'அறியாமையே துக்கத்திற்கு மிக முக்கியமான காரணம்.'),
  ('sai', 'Truth has no fear; Untruth shivers at every shadow.', 'உண்மைக்கு பயம் இல்லை; பொய் ஒவ்வொரு நிழலிலும் நடுங்கும்.'),
  ('sai', 'Love is the scarcest article today.', 'இன்று மிகவும் அரிதான பொருள் அன்பு.'),
  ('sai', 'Being a good example is the best form of service.', 'நல்ல முன்னுதாரணமாக இருப்பதே சேவையின் சிறந்த வடிவம்.'),
  ('sai', 'LOVE lives by giving and forgiving. Self lives by getting and forgetting.', 'அன்பு கொடுத்தும் மன்னித்தும் வாழும்; சுயநலம் பெற்றும் மறந்தும் வாழும்.'),
  ('sai', 'God is the doer; you are but the instrument.', 'இறைவனே செய்பவன்; நீ வெறும் கருவி மட்டுமே.'),
  ('sai', 'Duty without Love is deplorable; duty with Love is desirable; Love without duty is divine.', 'அன்பற்ற கடமை வருந்தத்தக்கது; அன்போடு கூடிய கடமை விரும்பத்தக்கது; கடமையற்ற அன்பு தெய்வீகமானது.'),
  ('sai', 'Do not get attached to worldly things; be in the world but do not let the world be in you.', 'உலக விஷயங்களில் பற்று வேண்டாம்; உலகில் இரு, ஆனால் உலகம் உனக்குள் இருக்க விடாதே.'),
  ('sai', 'The grace of God is like insurance; it will help you in your time of need without any limit.', 'இறைவனின் அருள் காப்பீட்டைப் போன்றது; தேவைப்படும் நேரத்தில் வரம்பின்றி உதவும்.'),
  ('sai', 'You cannot see Me, but I am the light you see by. You cannot hear Me, but I am the sound you hear by.', 'என்னை காண முடியாது, ஆனால் நீ பார்க்கும் ஒளி நானே. என்னை கேட்க முடியாது, ஆனால் நீ கேட்கும் ஒலி நானே.'),
  ('sai', 'Have constructive thoughts, consoling words, compassionate acts.', 'ஆக்கபூர்வமான எண்ணங்கள், ஆறுதல்படுத்தும் வார்த்தைகள், கருணையான செயல்கள் கொள்.'),
  ('sai', 'Each man carries his destiny in his own hands.', 'ஒவ்வொருவனும் தன் விதியை தன் கைகளிலேயே கொண்டிருக்கிறான்.'),
  ('sai', 'Friendship is the expression of unshakable Love — Love that is noble, pure, free from desire or egoism.', 'நட்பு என்பது அசைக்கமுடியாத அன்பின் வெளிப்பாடு — உன்னதமான, தூய்மையான, ஆசையும் அகங்காரமும் இல்லாத அன்பு.'),
  ('sai', 'I am you; you are Me. You are the waves; I am the ocean.', 'நான் நீ; நீ நான். நீ அலைகள்; நான் கடல்.'),
  ('sai', 'Teachers must be examples of Love and Truth.', 'ஆசிரியர்கள் அன்பின் மற்றும் உண்மையின் முன்னுதாரணமாக இருக்கவேண்டும்.'),
  ('sai', 'The wise are those who know the Self.', 'ஆத்மாவை அறிந்தவரே ஞானியர்.'),
  ('sai', 'Man will realize his mission on earth when he knows himself as divine and reveres others as divine.', 'தன்னை தெய்வீகமாக அறிந்து, மற்றவரையும் தெய்வீகமாக போற்றும்போதே மனிதன் தன் பூமி இயக்கத்தை உணர்வான்.'),
  ('sai', 'So long as you say ''I am'', there is bound to be fear; but once you say ''I am God'', you get unconquerable strength.', '''நான் இருக்கிறேன்'' என்று சொல்லும் வரை பயம் உண்டு; ''நான் கடவுள்'' என்று உணரும்போது வெல்லமுடியாத வலிமை கிடைக்கும்.'),
  ('sai', 'Practice the vocabulary of Love — unlearn the language of hate and contempt.', 'அன்பின் வார்த்தைகளை பயிற்சி செய் — வெறுப்பின் மொழியை மறந்துவிடு.'),
  ('sai', 'Each country is but a room in the mansion of God.', 'ஒவ்வொரு நாடும் இறைவனின் மாளிகையில் ஒரு அறை மட்டுமே.'),
  ('sai', 'God is in you, around you, behind you, above you, beside you.', 'இறைவன் உனக்குள் இருக்கிறான், உன்னை சுற்றி இருக்கிறான், உன் பின்னால், உன் மேலே, உன் பக்கத்திலும் இருக்கிறான்.'),
  ('sai', 'Of all righteous acts, help rendered to those needing it is the most righteous.', 'எல்லா நல்ல செயல்களிலும், தேவைப்படுபவர்களுக்கு உதவுவதே மிகவும் நீதியான செயல்.'),
  ('sai', 'Faith is like our life breath; it is impossible to live even a minute without faith.', 'நம்பிக்கை நம் உயிர் மூச்சைப் போன்றது; நம்பிக்கையின்றி ஒரு நிமிடமும் வாழ இயலாது.'),
  ('sai', 'Surrender the fruit of action to the Lord; that is real sacrifice.', 'செயலின் பலனை இறைவனிடம் சமர்பிப்பதே உண்மையான தியாகம்.'),
  ('sai', 'Education should build character.', 'கல்வி நற்குணத்தை கட்டியெழுப்பவேண்டும்.'),
  ('sai', 'It is Truth and Truth alone that is one''s real friend and relative.', 'உண்மை மட்டுமே உண்மையான நண்பனும் உறவும்.'),
  ('sai', 'Teachers are reservoirs from which, through the process of education, students draw the water of life.', 'ஆசிரியர்கள் நீர்த்தேக்கங்கள் போன்றவர்கள்; கல்வி என்ற செயல்முறை மூலம் மாணவர்கள் வாழ்வு நீரை அங்கிருந்து எடுக்கிறார்கள்.'),
  ('sai', 'The cultivation of Human Values alone is Education.', 'மனித மதிப்புகளை வளர்ப்பதே கல்வி ஆகும்.'),
  ('sai', 'Life is a challenge — meet it. Life is a dream — realize it. Life is Love — enjoy it.', 'வாழ்க்கை ஒரு சவால் — அதை எதிர்கொள். வாழ்க்கை ஒரு கனவு — அதை உணர். வாழ்க்கை அன்பு — அதை அனுபவி.'),
  ('sai', 'Have no desires to place before God; whatever He does with you is the gift He likes best to give you.', 'இறைவனிடம் ஆசைகள் வேண்டாம்; அவன் என்ன செய்தாலும் அதுவே அவன் கொடுக்க விரும்பும் சிறந்த பரிசு.'),
  ('sai', 'Unity is divinity; purity is enlightenment.', 'ஒற்றுமையே தெய்வீகம்; தூய்மையே ஞானம்.'),
  ('sai', 'Reason can prevail only when arguments are advanced without the whipping up of sound.', 'சத்தம் இல்லாமல் சொல்லப்படும் வாதங்களிலேயே பகுத்தறிவு வெல்ல முடியும்.'),
  ('sai', 'Your thoughts, words, and deeds will shape others, and theirs will shape you.', 'உன் எண்ணங்கள், வார்த்தைகள், செயல்கள் மற்றவரை உருவாக்கும்; அவர்களுடையவை உன்னை உருவாக்கும்.'),
  ('sai', 'By eating flesh one develops violent tendencies and animal diseases.', 'இறைச்சி சாப்பிடுவதால் வன்முறை மனோபாவமும் மிருக நோய்களும் உண்டாகும்.'),
  ('sai', 'Peace that pervades the heart can never be shaken; only this kind of Peace is worthy of the name.', 'இதயத்தில் நிலவும் அமைதி ஒருபோதும் அசைக்கப்பட முடியாது; இத்தகைய அமைதியே உண்மையான அமைதி.'),
  ('sai', 'As close as you are to God, so close is God to you.', 'நீ இறைவனுக்கு எவ்வளவு நெருக்கமோ, இறைவனும் உனக்கு அவ்வளவு நெருக்கமாக இருக்கிறான்.'),
  ('sai', 'Immortality is the fruit of sacrifice.', 'தியாகத்தின் பலனே அமரத்துவம்.'),
  ('sai', 'When you feel you cannot do good, at least desist from doing evil.', 'நன்மை செய்ய இயலாவிட்டாலும், தீமை செய்வதை விடு.'),
  ('sai', 'Love seeks no reward; Love is its own reward.', 'அன்பு பலனை எதிர்பார்க்காது; அன்பே அன்பின் பலன்.'),
  ('sai', 'The mind sees separateness; Love sees unity.', 'மனம் பிரிவினையை காண்கிறது; அன்பு ஒற்றுமையை காண்கிறது.'),
  ('sai', 'God is the life-breath of every soul.', 'இறைவன் ஒவ்வொரு ஆத்மாவின் உயிர் மூச்சு.'),
  ('sai', 'Patience is all the strength that man needs.', 'பொறுமையே மனிதனுக்கு தேவையான எல்லா வலிமையும்.'),
  ('sai', 'You must welcome tests because they give you confidence and ensure promotion.', 'சோதனைகளை வரவேற்க வேண்டும்; ஏனெனில் அவை நம்பிக்கையை தரும், முன்னேற்றத்தை உறுதி செய்யும்.'),
  ('sai', 'Spiritual progress is right living, good conduct, moral behavior.', 'சரியான வாழ்க்கை, நல்ல நடத்தை, ஒழுக்கமான நடவடிக்கை — இவையே ஆன்மீக முன்னேற்றம்.'),
  ('sai', 'LOVE must express itself as SERVICE.', 'அன்பு சேவையாக வெளிப்படவேண்டும்.'),
  ('sai', 'Devotion is not a uniform to be worn on certain days and then put aside.', 'பக்தி சில நாட்கள் மட்டும் அணிந்துகொள்ளும் சீருடை அல்ல.'),
  ('sai', 'When the road ends and the goal is gained, the pilgrim finds that he has traveled only from himself to himself.', 'வழி முடியும்போது, யாத்திரிகன் தான் தன்னிடமிருந்து தன்னிடமே பயணித்தான் என்று உணர்வான்.'),
  ('sai', 'Whatever the trouble, however great the sorrow, persist and win by recollecting the Lord.', 'எத்தகைய துன்பமாக இருந்தாலும், இறைவனை நினைத்து விடாமுயற்சியுடன் வெற்றி பெறு.'),
  ('sai', 'All things in creation are subject to the law of change; man too is subject to this law.', 'படைப்பில் எல்லாமே மாற்றத்தின் விதிக்கு உட்பட்டவை; மனிதனும் இந்த விதிக்கு கட்டுப்பட்டவனே.'),
  ('sai', 'Renunciation is the power of battling against evil forces and holding the mind in check.', 'தியாகம் என்பது தீய சக்திகளை எதிர்த்து போராடும் வலிமை; மனதை கட்டுப்படுத்தும் சக்தி.'),
  ('sai', 'Good company is important; it helps to cultivate good qualities.', 'நல்ல தோழமை முக்கியமானது; அது நல்ல குணங்களை வளர்க்க உதவும்.'),
  ('sai', 'Mine, not thine — this sense of greed is the root of all evil.', '''என்னுடையது, உன்னுடையது அல்ல'' என்ற பேராசை உணர்வே எல்லா தீமையின் வேர்.'),
  ('sai', 'The beauty of life depends upon our good habits.', 'வாழ்க்கையின் அழகு நம் நல்ல பழக்கங்களிலேயே இருக்கிறது.'),
  ('sai', 'God is all Names and all forms.', 'இறைவன் எல்லா நாமங்களும் எல்லா வடிவங்களும் ஆவான்.'),
  ('sai', 'If you honour your mother, the Mother of the Universe will guard you against harm.', 'உன் தாயை மதித்தால், அண்டத்தின் தாயார் உன்னை காப்பாற்றுவாள்.'),
  ('sai', 'Whenever and wherever you put yourself in touch with God, that is the state of meditation.', 'எப்போது, எங்கு இறைவனோடு இணைந்திருந்தாலும் அதுவே தியான நிலை.'),
  ('sai', 'Make the home a seat of harmony.', 'வீட்டை நல்லிணக்கத்தின் இருக்கையாக மாற்று.'),
  ('sai', 'The same current activates all.', 'அதே மின்னோட்டம் அனைவரையும் இயக்குகிறது.'),
  ('sai', 'All spiritual practice must be directed to the removal of the husk and the revelation of the kernel.', 'எல்லா ஆன்மீக பயிற்சியும் ஓட்டை நீக்கி, உள்ளிருக்கும் உண்மையை வெளிப்படுத்துவதை நோக்கியதாக இருக்கவேண்டும்.'),
  ('sai', 'Learn to speak what you feel, and act what you speak.', 'உணர்வதை பேசுவதை கற்றுக்கொள்; பேசுவதை செய்வதை கற்றுக்கொள்.'),
  ('sai', 'God is neither distant nor distinct from you.', 'இறைவன் உனக்கு தூரமானவனும் அல்ல, வேறானவனும் அல்ல.'),
  ('sai', 'God gave you time, space, cause, material, idea, skill, chance and fortune — why feel you are the doer?', 'காலம், இடம், காரணம், பொருள், யோசனை, திறன், வாய்ப்பு, அதிர்ஷ்டம் எல்லாம் இறைவனே கொடுத்தான் — நீ ஏன் செய்பவன் என்று நினைக்கிறாய்?'),
  ('sai', 'Food should not be too salty, too hot, too bitter, too sweet, too sour.', 'உணவு அதிக உப்பாகவோ, அதிக காரமாகவோ, கசப்பாகவோ, இனிப்பாகவோ, புளிப்பாகவோ இருக்கக்கூடாது.'),
  ('sai', 'Too much food results in dullness of mind.', 'அதிகமான உணவு மனதை மந்தமாக்கும்.'),
  ('sai', 'A language is as sweet as the tongues of the speakers.', 'ஒரு மொழி, அதை பேசுபவர்களின் நாவு எவ்வளவு இனிமையோ அவ்வளவு இனிமையானது.'),
  ('sai', 'God is ONE without a second. The service of man is the only means by which you can serve God.', 'இறைவன் ஒருவனே, இரண்டில்லை. மனிதனுக்கு சேவை செய்வதே இறைவனுக்கு சேவை செய்யும் ஒரே வழி.'),
  ('sai', 'Do not use poisonous words against anyone; words wound more fatally than even arrows.', 'யாருக்கும் நஞ்சுள்ள வார்த்தைகளை உபயோகிக்காதே; வார்த்தைகள் அம்புகளைவிட கொடியதாக காயப்படுத்தும்.'),
  ('sai', 'Be simple and sincere.', 'எளிமையாக இரு, நேர்மையாக இரு.'),
  ('sai', 'With effort and prayer destiny can be attained.', 'முயற்சியாலும் பிரார்த்தனையாலும் விதியை அடையலாம்.'),
  ('sai', 'Follow the Master, face the devil, fight to the end, finish the game.', 'குருவை பின்பற்று, தீமையை எதிர்கொள், முடிவுவரை போராடு, விளையாட்டை முடி.'),
  ('sai', 'Discipline is the mark of intelligent living.', 'கட்டுப்பாடே அறிவுள்ள வாழ்க்கையின் அடையாளம்.'),
  ('sai', 'Every experience that is drawn through any of the senses has an effect on one''s health.', 'ஐம்புலன்கள் வழியாக அனுபவிக்கும் ஒவ்வொன்றும் ஆரோக்கியத்தை பாதிக்கும்.'),
  ('sai', 'When calamity approaches, discrimination departs.', 'பேரிடர் நெருங்கும்போது விவேகம் வெளியேறும்.'),
  ('sai', 'A man''s well-being depends upon his degree of contentment.', 'மனிதனின் நலன் அவனின் திருப்தியின் அளவைப்பொறுத்தது.'),
  ('sai', 'Real happiness lies within you.', 'உண்மையான மகிழ்ச்சி உனக்குள்ளேயே இருக்கிறது.'),
  ('sai', 'Love all beings; that is enough.', 'எல்லா உயிர்களையும் நேசி; அது போதும்.'),
  ('sai', 'The mind fixed in the awareness of the ONE is like a rock — unaffected by doubt, stable, secure.', 'ஒன்றை உணர்வில் நிலைநிறுத்திய மனம் பாறையைப் போன்றது — சந்தேகத்தால் அசைக்கப்படாது, நிலையானது, பாதுகாப்பானது.'),
  ('sai', 'When his mind is slave to discontent, anger and envy, he cannot have peace and happiness.', 'மனம் அதிருப்தி, கோபம், பொறாமைக்கு அடிமையானால் அமைதியும் மகிழ்ச்சியும் கிட்டாது.'),
  ('sai', 'Take failure and victory coolly.', 'தோல்வியையும் வெற்றியையும் சமநிலையுடன் எடுத்துக்கொள்.'),
  ('sai', 'Hear no evil, see no evil, do no evil — and you will be free of fear.', 'தீமையை கேட்காதே, தீமையை பாராதே, தீமை செய்யாதே — அப்போது பயமிலிருந்து விடுதலையாவாய்.'),
  ('sai', 'When you kill an animal you give him suffering. God is in every creature — how can you give such pain?', 'மிருகத்தை கொல்லும்போது அதற்கு துன்பம் கொடுக்கிறாய். இறைவன் ஒவ்வொரு உயிரிலும் இருக்கிறான் — எப்படி இந்த வலியை கொடுக்கலாம்?'),
  ('sai', 'God first; the world next; myself last.', 'இறைவன் முதலில்; உலகம் அடுத்து; நான் இறுதியில்.'),
  ('sai', 'My birthday is the date when divinity blossoms in your heart.', 'தெய்வீகம் உன் இதயத்தில் மலர்ந்த நாளே என் பிறந்தநாள்.'),
  ('periyava', 'One must not keep a long face, wear a scowl or keep lamenting one''s hardships.', 'முகத்தை தொங்கவிட்டுக்கொண்டோ, கோபமான முகத்துடனோ, கஷ்டங்களை புலம்பியபடியோ இருக்கக்கூடாது.'),
  ('periyava', 'If you lose your cool you will be a burden to yourself as well as to others.', 'மனநிலையை இழந்தால், நீங்கள் உங்களுக்கும் மற்றவர்களுக்கும் சுமையாக மாறுவீர்கள்.'),
  ('periyava', 'Anayasa means not to feel any mental strain.', 'அனாயாசம் என்பது எந்த மனக்கஷ்டத்தையும் உணராமல் இருப்பதே ஆகும்.'),
  ('periyava', 'Obstacles, inevitable to any work or enterprise, must not cause you any mental strain.', 'எந்த செயலிலும் வரும் தடைகள் உங்களுக்கு மன இறுக்கத்தை ஏற்படுத்தக்கூடாது.'),
  ('periyava', 'Develop the attitude that everything happens according to the will of the Lord.', 'எல்லாம் இறைவனின் திருவுளப்படியே நடக்கிறது என்ற மனோபாவத்தை வளர்த்துக்கொள்ளுங்கள்.'),
  ('periyava', 'Purity is to be maintained in all matters such as bathing, dress, food etc.', 'குளித்தல், உடை, உணவு என அனைத்திலும் தூய்மை பேணப்படவேண்டும்.'),
  ('periyava', 'Cleanliness makes you happy and it even appeases your hunger.', 'தூய்மை உங்களுக்கு மகிழ்ச்சியை தரும்; அது பசியையும்கூட அடக்கும்.'),
  ('periyava', 'Heart burning caused by another man''s prosperity is jealousy.', 'மற்றவரின் செழிப்பால் மனம் எரிவதே பொறாமை ஆகும்.'),
  ('periyava', 'We ought to have love and compassion for all and ought to be patient and forgiving.', 'அனைவர் மீதும் அன்பும் கருணையும் கொண்டு, பொறுமையுடனும் மன்னிக்கும் குணத்துடனும் இருக்கவேண்டும்.'),
  ('periyava', 'We must not envy people their higher status even if they be less deserving.', 'தகுதி இல்லாதவர்களுக்கும் உயர் நிலை கிடைத்தாலும் நாம் பொறாமைப்படக்கூடாது.'),
  ('periyava', 'When adversities overtake us, we blame God and complain that He is blind to our misfortunes.', 'துன்பங்கள் வரும்போது, இறைவன் நம் துயரங்களை காணவில்லை என்று குற்றம் சாட்டுகிறோம்.'),
  ('periyava', 'If we indulge in a little introspection, we will realize that our faults are enormous.', 'சற்று ஆத்மசோதனை செய்தால், நம் குறைகள் மிகப்பெரியவை என்று உணர்வோம்.'),
  ('periyava', 'Troubles are verily God''s grace to save us.', 'துன்பங்கள் உண்மையில் நம்மை காக்க இறைவன் அளிக்கும் அருளே ஆகும்.'),
  ('periyava', 'In our inability to visualize the past and the future, we complain when we suffer in the present.', 'கடந்த காலத்தையும் எதிர்காலத்தையும் காண இயலாமல், நிகழ்காலத்தில் மட்டும் புலம்புகிறோம்.'),
  ('periyava', 'Neither the raw fruit nor the tree wants to leave each other. But when ripe, this attachment disappears.', 'பழமும் மரமும் பிரிய விரும்பாது; ஆனால் பழம் முற்றும்போது இந்த பற்று தானாக விலகும்.'),
  ('periyava', 'We cannot overcome anger, jealousy, passion in the beginning; but we must ponder why we undergo these.', 'கோபம், பொறாமை, ஆசை இவற்றை ஆரம்பத்தில் வெல்ல இயலாது; ஆனால் இவை ஏன் வருகின்றன என்று சிந்திக்கவேண்டும்.'),
  ('periyava', 'By education we realize Truth.', 'கல்வியின் மூலம் நாம் உண்மையை உணர்கிறோம்.'),
  ('periyava', 'By a process of gradual elimination of all that is imaginary, when we arrive at truth, that Truth is God.', 'கற்பனையானவற்றை ஒவ்வொன்றாக நீக்கி உண்மையை அடையும்போது, அந்த உண்மையே இறைவன் ஆகும்.'),
  ('periyava', 'To think of Him with real devotion is the fruit of education.', 'உண்மையான பக்தியுடன் அவனை நினைப்பதே கல்வியின் பயன்.'),
  ('periyava', 'Parameswara and Sriman Narayana are one and the same in reality.', 'பரமேஸ்வரனும் ஸ்ரீமன் நாராயணனும் உண்மையில் ஒன்றே.'),
  ('periyava', 'Vedanta teaches the way for the removal of sorrow.', 'வேதாந்தம் துக்கத்தை போக்கும் வழியை கற்றுத்தருகிறது.'),
  ('periyava', 'If there is no desire, there will be no effort and no sin.', 'ஆசை இல்லையெனில் முயற்சியும் இல்லை; பாவமும் இல்லை.'),
  ('periyava', 'The first step in enlightenment is to make a man truly a man, by ensuring he does not live on an animal level.', 'ஞானத்தின் முதல் படி, மனிதன் மிருக நிலையில் வாழாமல் உண்மையான மனிதனாக இருப்பதை உறுதி செய்வதே.'),
  ('periyava', 'All religions have the goal that man must be rendered good.', 'மனிதனை நல்லவனாக மாற்றுவதே எல்லா மதங்களின் குறிக்கோளும் ஆகும்.'),
  ('periyava', 'All religions speak in one voice — love, humility, serenity, and spirit of sacrifice.', 'அன்பு, அடக்கம், அமைதி, தியாக மனப்பான்மை என்பவற்றை எல்லா மதங்களும் ஒரே குரலில் போதிக்கின்றன.'),
  ('periyava', 'There need be no doubt about the dharma we ought to follow.', 'நாம் பின்பற்றவேண்டிய தர்மத்தில் எந்த சந்தேகமும் வேண்டியதில்லை.'),
  ('periyava', 'Follow the dharma practiced by the great men of the past.', 'கடந்த காலத்தில் மகான்கள் அனுஷ்டித்த தர்மத்தை பின்பற்றுவதே சிறந்தது.'),
  ('periyava', 'Dharma is after-life insurance; in this life too it is dharma that gives us peace.', 'தர்மம் மறுவாழ்வுக்கான காப்பீடு; இந்த வாழ்விலும் தர்மமே அமைதி தரும்.'),
  ('periyava', 'Sorrow and anger are two forms of unrequited desire.', 'துக்கமும் கோபமும் நிறைவேறாத ஆசையின் இரண்டு வடிவங்கள்.'),
  ('periyava', 'Anger is packed with more evil power than even desire.', 'கோபம், ஆசையைவிட அதிக தீய சக்தி கொண்டது.'),
  ('periyava', 'Desire, anger, hatred, fear — all these appertain to the mind, not to the Self.', 'ஆசை, கோபம், வெறுப்பு, பயம் — இவை மனதிற்கு உரியவை; ஆத்மாவிற்கு இல்லை.'),
  ('periyava', 'When we practice ahimsa, anger will naturally give way.', 'அகிம்சையை பயிற்சி செய்யும்போது கோபம் தானாகவே விலகும்.'),
  ('periyava', 'Truthful words that create good are the product of a mind free from desire and anger.', 'நன்மை செய்யும் உண்மையான வார்த்தைகள், ஆசையும் கோபமும் இல்லாத மனதிலிருந்தே வரும்.'),
  ('periyava', 'The purpose of Vedic rituals is to take us, by degrees, beyond the three gunas.', 'வேத சடங்குகளின் நோக்கம் நம்மை படிப்படியாக மூன்று குணங்களுக்கும் அப்பாற்சென்று சேர்ப்பதே.'),
  ('periyava', 'Silence is a great teacher.', 'மௌனம் மிகப்பெரிய குரு.'),
  ('periyava', 'Without discipline there can be no real progress.', 'கட்டுப்பாடு இல்லாமல் உண்மையான முன்னேற்றம் இல்லை.'),
  ('periyava', 'God''s grace is available to all; only our impurity stops us from receiving it.', 'இறைவனின் அருள் அனைவருக்கும் கிடைக்கும்; நம் மாசுதான் அதை தடுக்கிறது.'),
  ('periyava', 'Service to man is service to God.', 'மனிதனுக்கு செய்யும் சேவையே இறைவனுக்கு செய்யும் சேவை.'),
  ('periyava', 'A contented man is truly wealthy.', 'திருப்தியுள்ளவனே உண்மையான செல்வந்தன்.'),
  ('periyava', 'Prayer done with full concentration reaches God directly.', 'முழு ஒருமுகப்படுத்தலுடன் செய்யும் பிரார்த்தனை இறைவனை நேரடியாக அடையும்.'),
  ('periyava', 'Do not waste food; it is verily the form of God.', 'உணவை வீணாக்காதே; அது இறைவனின் வடிவமே.'),
  ('periyava', 'A man who does his duty without expecting fruit is truly free.', 'பலனை எதிர்பாராமல் கடமையை செய்யும் மனிதனே உண்மையில் சுதந்திரமானவன்.'),
  ('periyava', 'The Vedas are not mere rituals; they are the eternal voice of truth.', 'வேதங்கள் வெறும் சடங்குகள் அல்ல; அவை உண்மையின் நித்திய குரல்.'),
  ('periyava', 'A nation grows strong when its people follow dharma.', 'மக்கள் தர்மத்தை பின்பற்றும்போது தேசம் வலிமையடைகிறது.'),
  ('periyava', 'The mother is the first teacher of every child.', 'தாயே ஒவ்வொரு குழந்தைக்கும் முதல் குரு.'),
  ('periyava', 'Arrogance destroys the noblest qualities of man.', 'அகங்காரம் மனிதனின் உன்னதமான குணங்களை அழித்துவிடும்.'),
  ('periyava', 'A mind at peace is the greatest treasure.', 'அமைதியான மனமே மிகப்பெரிய பொக்கிஷம்.'),
  ('periyava', 'Speak the truth, but let it be sweet.', 'உண்மையை பேசு, ஆனால் அது இனிமையாக இருக்கட்டும்.'),
  ('periyava', 'Greed is the root of all suffering.', 'பேராசையே எல்லா துன்பங்களுக்கும் வேர்.'),
  ('periyava', 'Our ancestors followed a way of life that was tested by time; we must not discard it lightly.', 'நம் முன்னோர்கள் காலம் சோதித்த வாழ்க்கை முறையை பின்பற்றினர்; அதை நாம் அலட்சியமாக கைவிடக்கூடாது.'),
  ('periyava', 'Do not be hasty in speech or action.', 'சொல்லிலும் செயலிலும் அவசரப்படாதே.'),
  ('periyava', 'Compassion is the highest virtue.', 'கருணையே மிக உயர்ந்த நல்லொழுக்கம்.'),
  ('periyava', 'The cow is sacred; protect it as you would your own mother.', 'பசு புனிதமானது; அதை உன் தாயைப்போல காத்துக்கொள்.'),
  ('periyava', 'True renunciation is the renunciation of ego, not of objects.', 'உண்மையான துறவு, பொருட்களை விடுவது அல்ல — அகங்காரத்தை விடுவதே.'),
  ('periyava', 'Music and devotion uplift the soul.', 'இசையும் பக்தியும் ஆத்மாவை உயர்த்தும்.'),
  ('periyava', 'Even a little good done sincerely reaches God.', 'சிறிய நன்மை செய்யினும், அது நேர்மையுடன் செய்தால் இறைவனை அடையும்.'),
  ('periyava', 'The Ganga is not merely a river; it is a river of grace.', 'கங்கை வெறும் நதியல்ல; அது அருளின் நதி.'),
  ('periyava', 'Worship does not require wealth; it requires a pure heart.', 'வழிபாட்டிற்கு செல்வம் தேவையில்லை; தூய்மையான மனம் தேவை.'),
  ('periyava', 'Do not look down on anyone; every soul is a spark of the divine.', 'யாரையும் இகழாதே; ஒவ்வொரு ஆத்மாவும் தெய்வீகத்தின் தீப்பொறி.'),
  ('periyava', 'The scriptures were given not just to be read but to be lived.', 'நூல்கள் படிக்கமட்டும் அல்ல; வாழ்வதற்காகவே கொடுக்கப்பட்டன.'),
  ('periyava', 'Chant the name of God; it is the boat that will carry you across the ocean of birth and death.', 'இறைவனின் நாமத்தை ஜபி; அது பிறப்பு-இறப்பு என்ற கடலை கடக்கும் படகு.'),
  ('periyava', 'Surrender everything to God and be free from anxiety.', 'எல்லாவற்றையும் இறைவனிடம் சமர்பி; கவலையிலிருந்து விடுபடு.'),
  ('periyava', 'Ego is the veil that hides God from us.', 'அகம்பாவம் இறைவனை நம்மிடமிருந்து மறைக்கும் திரை.'),
  ('periyava', 'Those who harm cows harm themselves.', 'பசுவை துன்புறுத்துபவர்கள் தங்களையே துன்புறுத்துகிறார்கள்.'),
  ('periyava', 'Character is more important than talent.', 'திறமையைவிட நற்குணம் அதிக முக்கியமானது.'),
  ('periyava', 'A good wife is the pillar of a happy household.', 'நல்ல மனைவியே இன்பமான குடும்பத்தின் தூண்.'),
  ('periyava', 'The purpose of life is to know God and become one with Him.', 'வாழ்க்கையின் நோக்கம் இறைவனை அறிவதும் அவனோடு ஒன்றாவதுமே.'),
  ('periyava', 'Never abandon your faith even in the darkest hour.', 'இருண்ட வேளையிலும் உன் நம்பிக்கையை கைவிடாதே.'),
  ('periyava', 'Fasting is a discipline for both body and mind.', 'உபவாசம் உடலுக்கும் மனதிற்கும் கட்டுப்பாட்டை தரும் ஒழுக்கம்.'),
  ('periyava', 'Water flows down and reaches the ocean; a humble soul flows to God.', 'நீர் தாழ்வாக ஓடி கடலை அடைவது போல, தாழ்மையான ஆத்மா இறைவனை அடையும்.'),
  ('periyava', 'Knowledge without action is useless.', 'செயலற்ற ஞானம் பயனற்றது.'),
  ('periyava', 'Spend every day in remembrance of God.', 'ஒவ்வொரு நாளும் இறைவனை நினைத்தே கழி.'),
  ('periyava', 'Respect your parents; they are your first gods.', 'உன் பெற்றோரை மதி; அவர்களே உன் முதல் தெய்வம்.'),
  ('periyava', 'Even the poorest man can worship God with sincerity.', 'மிகவும் ஏழையான மனிதனும் நேர்மையுடன் இறைவனை வழிபடலாம்.'),
  ('periyava', 'When the mind is still, God''s presence is felt.', 'மனம் அமைதியாக இருக்கும்போது இறைவனின் இருப்பு உணரப்படும்.'),
  ('periyava', 'Tradition is not a burden but a treasure.', 'பாரம்பரியம் சுமையல்ல; அது பொக்கிஷம்.'),
  ('periyava', 'Dharma protects those who protect it.', 'தர்மத்தை காப்பவரை தர்மம் காக்கும்.'),
  ('periyava', 'Do not be attracted by the glitter of the world.', 'உலகின் பொய்யான பளபளப்பால் ஈர்க்கப்படாதே.'),
  ('periyava', 'A simple life lived with devotion is worth more than a wealthy life without it.', 'பக்தியுடன் வாழும் எளிமையான வாழ்க்கை, பக்தியில்லா வசதியான வாழ்க்கையைவிட உயர்வானது.'),
  ('periyava', 'Real education makes a man humble, not arrogant.', 'உண்மையான கல்வி மனிதனை தாழ்மையாக்கும்; அகங்காரமாக அல்ல.'),
  ('periyava', 'Just as fire purifies gold, suffering purifies the soul.', 'தீ தங்கத்தை சுத்திகரிப்பது போல, துன்பம் ஆத்மாவை சுத்திகரிக்கும்.'),
  ('periyava', 'Gain mastery over the five senses and you will gain mastery over the world.', 'ஐம்புலன்களை வெல்பவன் உலகையே வெல்வான்.'),
  ('periyava', 'Even if you cannot do great things, do small things with great love.', 'பெரிய காரியங்கள் செய்ய இயலாவிட்டாலும், சிறிய காரியங்களை பெரிய அன்புடன் செய்.'),
  ('periyava', 'Do not postpone good deeds.', 'நல்ல செயல்களை ஒத்திவைக்காதே.'),
  ('periyava', 'The one who controls his tongue controls his destiny.', 'நாவை கட்டுப்படுத்துபவன் தன் விதியை கட்டுப்படுத்துகிறான்.'),
  ('periyava', 'True knowledge removes the differences between oneself and others.', 'உண்மையான ஞானம் தன்னுக்கும் மற்றவருக்கும் உள்ள வேற்றுமைகளை நீக்கும்.'),
  ('periyava', 'Pilgrimage is not merely physical travel; it is inner purification.', 'யாத்திரை வெறும் உடல் பயணம் அல்ல; அது உள் சுத்தீகரணம்.'),
  ('periyava', 'To feed the hungry is to feed God himself.', 'பசித்தவனுக்கு உணவிடுவது இறைவனுக்கே உணவிடுவதாகும்.'),
  ('periyava', 'God is not partial; He showers His grace equally on all.', 'இறைவன் பக்கபாதம் காட்டுவதில்லை; அவன் அருளை அனைவர் மீதும் சமமாக பொழிகிறான்.'),
  ('periyava', 'Ahimsa is not just not killing; it is the active expression of love.', 'அகிம்சை என்பது வெறுமனே கொல்லாமல் இருப்பதல்ல; அது அன்பை செயலாக வெளிப்படுத்துவது.'),
  ('periyava', 'Learn from everything — even adversity is a teacher.', 'எல்லாவற்றிலிருந்தும் கற்றுக்கொள்; துன்பமும் ஒரு குருவே.'),
  ('periyava', 'The body is a temple; treat it with respect.', 'உடல் ஒரு கோவில்; அதை மரியாதையுடன் நடத்து.'),
  ('periyava', 'A man who cannot forgive destroys the bridge over which he himself must pass.', 'மன்னிக்க மறுப்பவன் தான் கடக்கவேண்டிய பாலத்தையே அழிக்கிறான்.'),
  ('periyava', 'Yoga is not merely posture; it is union with the divine.', 'யோகம் என்பது வெறும் உடல் நிலைகள் அல்ல; அது தெய்வத்தோடு ஒன்றுகூடுவதே.'),
  ('periyava', 'The world is a school; every experience is a lesson.', 'உலகம் ஒரு பள்ளி; ஒவ்வொரு அனுபவமும் ஒரு பாடம்.'),
  ('periyava', 'Keep your mind on God and your hands in work.', 'மனதை இறைவனிடம் வை; கைகளை வேலையில் வை.'),
  ('periyava', 'Charity given with a pure heart multiplies a thousandfold.', 'தூய மனதுடன் கொடுக்கும் தானம் ஆயிரமடங்காக பெருகும்.'),
  ('periyava', 'Do not measure your worth by the opinions of others.', 'மற்றவர்களின் கருத்துகளால் உன் மதிப்பை அளவிடாதே.'),
  ('periyava', 'A devotee who constantly remembers God has nothing to fear.', 'எப்போதும் இறைவனை நினைக்கும் பக்தனுக்கு எதுவும் பயமில்லை.'),
  ('periyava', 'The highest goal of life is Moksha — liberation from the cycle of birth and death.', 'வாழ்க்கையின் மிக உயர்ந்த இலக்கு மோட்சம் — பிறப்பு-இறப்பு சுழலிலிருந்து விடுதலை.');
