"""
run_schema_fix.py
Sends schema fix SQL statements to Supabase using the REST API.
Run: python quote/run_schema_fix.py
"""
import urllib.request
import urllib.error
import json
import os

SUPABASE_URL = "https://zkzotagctwqthxypczej.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inprem90YWdjdHdxdGh4eXBjemVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAxMjc3NzMsImV4cCI6MjA5NTcwMzc3M30.8xL23N-3MfbrXOA-ljsOnFy_LIDKCSxbYfHRzvMqCak"

# Each SQL statement to run
SQL_STATEMENTS = [
    "ALTER TABLE public.members ALTER COLUMN phone DROP NOT NULL",
    """CREATE TABLE IF NOT EXISTS public.event_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now() NOT NULL
)""",
    "ALTER TABLE public.event_categories ENABLE ROW LEVEL SECURITY",
    'DROP POLICY IF EXISTS "Public read event categories" ON public.event_categories',
    'DROP POLICY IF EXISTS "Anyone can manage event categories" ON public.event_categories',
    """CREATE POLICY "Anyone can manage event categories"
  ON public.event_categories FOR ALL
  USING (true)
  WITH CHECK (true)""",
    """CREATE POLICY "Public read event categories"
  ON public.event_categories FOR SELECT
  USING (true)""",
    """INSERT INTO public.event_categories (name)
VALUES ('Bhajans'), ('Seva'), ('Study Circle'), ('Celebration')
ON CONFLICT (name) DO NOTHING"""
]


def run_sql(sql):
    url = f"{SUPABASE_URL}/rest/v1/rpc/exec_sql"
    payload = json.dumps({"sql": sql}).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=payload,
        headers={
            "Content-Type": "application/json",
            "apikey": SUPABASE_ANON_KEY,
            "Authorization": f"Bearer {SUPABASE_ANON_KEY}",
        },
        method="POST"
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return resp.status, resp.read().decode()
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode()
    except Exception as ex:
        return 0, str(ex)


if __name__ == "__main__":
    print("Running Supabase schema fix...\n")
    for i, stmt in enumerate(SQL_STATEMENTS, 1):
        short = stmt.strip().split("\n")[0][:80]
        print(f"[{i}/{len(SQL_STATEMENTS)}] {short}")
        code, resp = run_sql(stmt)
        if code in (200, 201, 204):
            print(f"  OK (HTTP {code})\n")
        else:
            print(f"  FAIL HTTP {code}: {resp[:300]}\n")

    print("Done.")
